trigger: none

parameters:
  - name: repoOption
    displayName: "Selecciona el repositorio"
    type: string
    default: springboot
    values:
      - springboot
      - react
      - ejemplo-repo

variables:
  springbootRepo: "https://github.com/Adrian-Bastidas/AqrGSprinboot"
  react: "https://github.com/Adrian-Bastidas/ArqGReact"
  ejemplo-repoRepo: "https://github.com/usuario/ejemplo-repo"

pool:
  name: Default

steps:
  - script: |
      echo "Opción seleccionada: ${{ parameters.repoOption }}"

      if [ "${{ parameters.repoOption }}" = "springboot" ]; then
        echo "Repositorio: $(springbootRepo)"
      elif [ "${{ parameters.repoOption }}" = "otro-repo" ]; then
        echo "Repositorio: $(react)"
      elif [ "${{ parameters.repoOption }}" = "ejemplo-repo" ]; then
        echo "Repositorio: $(ejemplo-repoRepo)"
      fi
    displayName: "Imprimir repositorio seleccionado"
