jobs:
  - job: Diagnostico
    displayName: "Job 0 · Diagnóstico - Payload recibido desde Port"
    pool:
      name: Default
    steps:
      - bash: |
          echo "newRepoName   : ${{ parameters.port_trigger.properties.newRepoName }}"
          echo "projectName   : ${{ parameters.port_trigger.properties.projectName }}"
          echo "repoTemplate  : ${{ parameters.port_trigger.properties.repoTemplate }}"
          echo "repoVisibility: ${{ parameters.port_trigger.properties.repoVisibility }}"
          echo "runId         : ${{ parameters.port_trigger.port_context.runId }}"
        displayName: "Imprimir todos los parámetros recibidos"
