trigger: none

parameters:
  - name: newRepoName
    type: string
  - name: projectName
    type: string
  - name: repoTemplate
    type: string
  - name: repoVisibility
    type: string
  - name: runId
    type: string

variables:
  - template: variables/variables.yml
  - group: github-secrets

stages:
  - stage: Pipeline
    displayName: "Creación de repositorio"
    jobs:
      - template: jobs/diagnostico.yml
        parameters:
          newRepoName: ${{ parameters.newRepoName }}
          projectName: ${{ parameters.projectName }}
          repoTemplate: ${{ parameters.repoTemplate }}
          repoVisibility: ${{ parameters.repoVisibility }}
          runId: ${{ parameters.runId }}

      - template: jobs/prerequisitos.yml

      - template: jobs/validacion.yml
        parameters:
          newRepoName: ${{ parameters.newRepoName }}
          projectName: ${{ parameters.projectName }}
          repoTemplate: ${{ parameters.repoTemplate }}

      - template: jobs/creacion-repositorio.yml
        parameters:
          newRepoName: ${{ parameters.newRepoName }}
          repoVisibility: ${{ parameters.repoVisibility }}

      - template: jobs/aplicar-template.yml
        parameters:
          projectName: ${{ parameters.projectName }}
          repoTemplate: ${{ parameters.repoTemplate }}
          newRepoName: ${{ parameters.newRepoName }}

      - template: jobs/proteccion-ramas.yml

      - template: jobs/resumen-final.yml

  - stage: update_run_success
    displayName: "Notificar éxito a Port"
    dependsOn: Pipeline
    condition: succeeded('Pipeline')
    jobs:
      - template: jobs/notificar-port.yml
        parameters:
          status: "SUCCESS"
          message: "Pipeline completed successfully!"
          runId: ${{ parameters.runId }}

  - stage: update_run_failed
    displayName: "Notificar fallo a Port"
    dependsOn: Pipeline
    condition: failed('Pipeline')
    jobs:
      - template: jobs/notificar-port.yml
        parameters:
          status: "FAILURE"
          message: "Pipeline failed!"
          runId: ${{ parameters.runId }}
