trigger: none

resources:
  webhooks:
    - webhook: port_trigger
      connection: port_trigger

variables:
  - template: variables/variables.yml
  - group: github-secrets
  - name: newRepoName
    value: $[ resources.triggerBody().properties.newRepoName ]
  - name: projectName
    value: $[ resources.triggerBody().properties.projectName ]
  - name: repoTemplate
    value: $[ resources.triggerBody().properties.repoTemplate ]
  - name: repoVisibility
    value: $[ resources.triggerBody().properties.repoVisibility ]
  - name: portRunId
    value: $[ resources.triggerBody().port_context.runId ]

stages:
  - stage: Pipeline
    displayName: "Creación de repositorio"
    jobs:
      - template: jobs/prerequisitos.yml

      - template: jobs/validacion.yml
        parameters:
          newRepoName: $(newRepoName)
          projectName: $(projectName)
          repoTemplate: $(repoTemplate)

      - template: jobs/creacion-repositorio.yml
        parameters:
          newRepoName: $(newRepoName)
          repoVisibility: $(repoVisibility)

      - template: jobs/aplicar-template.yml
        parameters:
          projectName: $(projectName)
          repoTemplate: $(repoTemplate)
          newRepoName: $(newRepoName)

      - template: jobs/proteccion-ramas.yml
      - template: jobs/resumen-final.yml

  - stage: update_run_success
    displayName: "Notificar éxito a Port"
    dependsOn: Pipeline
    condition: succeeded('Pipeline')
    jobs:
      - template: jobs/notificar-port.yml
        parameters:
          status: "SUCCESS"
          message: "Pipeline completed successfully!"
          runId: $(portRunId)

  - stage: update_run_failed
    displayName: "Notificar fallo a Port"
    dependsOn: Pipeline
    condition: failed('Pipeline')
    jobs:
      - template: jobs/notificar-port.yml
        parameters:
          status: "FAILURE"
          message: "Pipeline failed!"
          runId: $(portRunId)
